# Generated by Django 5.1.3 on 2025-04-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emargement',
            name='dateHeureDebut',
            field=models.DateTimeField(),
        ),
    ]
