# Generated by Django 5.1.3 on 2025-04-22 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0002_alter_emargement_dateheuredebut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='enseignant',
        ),
    ]
