# Generated by Django 5.1.3 on 2025-04-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0003_remove_cours_classe_remove_cours_enseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='niveau',
        ),
        migrations.AddField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaire.classe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaire.enseignant'),
        ),
    ]
