# Generated by Django 5.1.3 on 2025-04-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0003_evaluation_etudiant_alter_etudiant_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='coutA',
        ),
        migrations.AddField(
            model_name='inscription',
            name='montantRestant',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutInscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coutScolarite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fraisEtudeDossier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couts', to='secretaire.classe')),
            ],
        ),
    ]
