# Generated by Django 5.1.3 on 2025-04-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0004_remove_inscription_couta_inscription_montantrestant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='montantRestant',
        ),
    ]
